### ISSUE TITLE
covid contact-tracker like dp-3t feasible for any smart-watch? At least data-acq function.

### ISSUE THREAD

**Issue by porteusconf** [OpenWatchProject/readme#1]
Is it feasible for any compatible smart-watch to run at least the data-acquisition part of the contact-tracker apps being developed for covid like https://github.com/DP-3T These use anonymized bluetooth beacons, where key and mac-address is rolled every 15 minutes or so.  No gps/wifi/3g or anything besides btle needed while tracking. Some watch models known to work with OpenWatchProject are only about $70 USD currently, so this might be cost-effective alternative to cell-phone for contact-tracking.  Temperature monitoring a bonus.

One use case would be elderly and others without their own android/ios smartphone of their own. They  would certainly  know a health-care provider or other trusted person with a smartphone/computer where they could dump data collected by contact-tracking algorithm  running on the watch. QR-code on watch might possibly be involved.

**Comment by deadman96385** [comment]
It may be possible, but it really out of scope for this project sadly.
