### ISSUE TITLE
Does OpenWatch support "IQI i4 Pro" smartwatch?

### ISSUE THREAD

**Issue by avs3** [OpenWatchProject/readme#2]
Hello,

I have "IQI i4 Pro" smartwatch (MT6580, 2GB/16GB, no camera, Android 5.1, https://www.youtube.com/watch?v=RZrrrY-zv1c).
It's not in the confirmed working devices lists.

Does OpenWatch support it?

Thanks in advance

**Comment by deadman96385** [comment]
Harmony should work on it, but would need to be tested. If you would like you can join our telegram support channel

https://t.me/joinchat/DfKn4ElbICtT5Qm4Uq2mpA
